### ISSUE TITLE
Usability - Easy year selection

### ISSUE THREAD

**Issue by jpike88** [logbon72/angular-material-datetimepicker#11]
For things like date of birth, there needs to be an easier way to choose the year.

I have been trying to place an up/down arrow next to the year, and having it increment or decrement the date by one year when pressed.

The problem is that I'm trying to have that talk to the calendar display to trigger an update so it can re-center over the new date. Any suggestions?

Modifications made:

Modified the template variable:
`+ '                    <div class="dtp-actual-year">{{picker.currentDate.format("YYYY")}}</div>'`
`// new lines added below`
`+ '                    <div ng-click="picker.incrementYear(1)">year up</div>'`
`+ '                    <div ng-click="picker.incrementYear(-1)"class="dtp-actual-year">year down</div>'`

Function added after the `isPM` function:

`incrementYear: function (amount) {`
`this.selectDate(this.currentDate.add('year', amount));`
`}`

**Comment by jpike88** [comment]
With all due respect mate, I'm trying to make your project better. If you're going to make it open source, the least you could do is at least spend the 1-2 minutes to make a reply, so we can both benefit from it.

**Comment by logbon72** [comment]
Hey,

Sorry about that, thought I replied earlier. Please can you do a Pull Request for this?  

Regards

**Comment by jpike88** [comment]
Ah good! Have a look at what I posted, I'm not proposing a pull request (yet), I'm asking how best to have the year increment function trigger a re-centering of the calendar view, as I don't want to screw up the structure you've laid out.

**Comment by logbon72** [comment]
This was what I had in mind. On Android, it comes up when you tap the year.

**Comment by jpike88** [comment]
That seems to be quite a bit of work, although eventually it would be great if it did that.. but my method offers something fast, all it needs is one or two lines of code to allow the calendar update to trigger.

Do you see what my code is trying to do?

**Comment by jpike88** [comment]
Any comments....????

**Comment by jpike88** [comment]
... did you actually read my first post?

**Comment by jpike88** [comment]
Based on a lack of responsiveness on a very simple question, I'm going to have to abandon this library, sorry.

**Comment by tachyon-ops** [comment]
Hehh hard to produce open source these days. Anyway... 

Completly 100% agree with the fact that year selection has been a crap, that's why I am searching for a good alternative (well... but since It's open source, I am thinking in changing the templates). Just wondering if anyone has done a pull request?

There seams to be something on the source code 'selectYearBefore' and 'selectYearAfter' is there any directive to access them?

**Comment by logbon72** [comment]
> There seams to be something on the source code 'selectYearBefore' and 'selectYearAfter' is there any directive to access them?

@nmpribeiro this is from the Bootstrap version that was forked to create this plugin.

@jpike88 sincere apologies. I've been swamped with a lot of work lately.

**Comment by jpike88** [comment]
@logbon72 I appreciate your efforts. I am rooting for this library in the main Angular Material issues, I think that the only thing stopping it from being taken seriously is that it is presented in an md-dialog. For my use case, it doesn't bother me but I imagine it does for them.

I'm going to comment there and let them know that this handles year selection more easily and see their thoughts.

**Comment by tachyon-ops** [comment]
@logbon72 cool. thanks mate!
