### ISSUE TITLE
Cannot enter date time manually

### ISSUE THREAD

**Issue by naveendb92** [logbon72/angular-material-datetimepicker#118]
On click, everytime opens a datetime picker. 
1. Is it possible to enter the dates manually ?
2. Is it possible to clear the date that has been selected ?

**Comment by hexadecy** [comment]
1. https://github.com/beenote/angular-material-datetimepicker
edit-input="true"
The button to open the picker have to be added. 

2. Where you want the clear button, a X is ok? Normally I put a X button at then end of an input. I think IE and Edge put a x in the input sometime.

**Comment by naveendb92** [comment]
Yes. A small X button to clear the date would be fine I feel.

**Comment by hexadecy** [comment]
@naveendb92 please have a look
https://github.com/beenote/angular-material-datetimepicker/releases/tag/v1.8.5

**Comment by naveendb92** [comment]
@hexadecy first of all sorry for the late reply.
Thank you so much for adding the feature. Really appreciate your effort to resolve the user queries.
