### ISSUE TITLE
Clock looks horrible! Everything is messed up!

### ISSUE THREAD

**Issue by dragondgold** [logbon72/angular-material-datetimepicker#12]
I'm trying to use the date picker, I took the code from the examples and added it to my page:

```
<md-input-container class="col-md-2 col-md-offset-5" flex-gt-sm>
      <label>Time</label>
      <input mdc-datetime-picker="" date="false" time="true" type="text" id="time" short-time="true"
            placeholder="Time" min-date="minDate" format="hh:mm a" ng-model="time" class="md-input">
</md-input-container>
```

But the clock looks really bad and also the buttons are on the top!

![capture2](https://cloud.githubusercontent.com/assets/2932540/13537140/3c911702-e222-11e5-9e64-4ba91471f343.PNG)

Any idea about what could be the problem?

**Comment by logbon72** [comment]
Please ensure you add all the necessary CSS files. angular-material.css and material-datetimepicker.css

**Comment by dragondgold** [comment]
Yes, I have both files, angular-material.css and material-datetimepicker.css. angular-material.css is version `v0.9.0-rc3-master-f01afde`, is it ok?

**Comment by logbon72** [comment]
This project was developed on version `1.0.0-rc3` so please upgrade and see if it works.

**Comment by dragondgold** [comment]
@logbon72 great! Working perfectly now! Thank you!
