### ISSUE TITLE
There's a hanging console.log

### ISSUE THREAD

**Issue by jpike88** [logbon72/angular-material-datetimepicker#129]
https://github.com/logbon72/angular-material-datetimepicker/blob/307054486aec110fe6387a9ad86a9e91cb226a27/js/angular-material-datetimepicker.js#L229

**Comment by hexadecy** [comment]
Duplicate of #113 
Fixed long time ago in our fork:
https://github.com/beenote/angular-material-datetimepicker

**Comment by jpike88** [comment]
awesome, cheers!
