### ISSUE TITLE
Incorrect display of timepicker on internet explorer

### ISSUE THREAD

**Issue by gr7egor7** [logbon72/angular-material-datetimepicker#15]
On Internet Explorer 11 timepicker shows empty clock face, I cannot pick the time.

**Comment by logbon72** [comment]
Hey, can you attach a screenshot ?

**Comment by gr7egor7** [comment]
Yes, sure :
![img_17032016_212832](https://cloud.githubusercontent.com/assets/16045693/13900949/18e02ae4-ee13-11e5-9558-ec8db4760003.png)

**Comment by rafaelmagalhaes** [comment]
Hi, I have the latest version and im still getting that issue on IE 11

**Comment by sebastiendan** [comment]
Any updates on this?
