### ISSUE TITLE
year jumps to 2100 in IE11

### ISSUE THREAD

**Issue by d668** [logbon72/angular-material-datetimepicker#19]
![image](https://cloud.githubusercontent.com/assets/2155554/14059980/9121f68e-f34c-11e5-8e08-420ee47b517b.png)

**Comment by d668** [comment]
open datepicker, click few times arrow down, then click on a date. The year jumps to 2100

**Comment by ViDaNgEr** [comment]
This bug also occurred in other browser (Tested with Chrome and Edge)

**Comment by logbon72** [comment]
Fixed by PR https://github.com/logbon72/angular-material-datetimepicker/issues/29
