### ISSUE TITLE
ng-change is not supported

### ISSUE THREAD

**Issue by ViDaNgEr** [logbon72/angular-material-datetimepicker#22]
it should support ng-change.
The workaround is to use a $watch.

**Comment by k3v3n** [comment]
Indeed. It could be great if ng-change was supported.

**Comment by ViDaNgEr** [comment]
I will make a pull request probably next monday with the ng-change support

**Comment by otavioschwanck** [comment]
Please, i need ng-change =\

**Comment by tekand** [comment]
Created pull request for this issue. #57

**Comment by Dunos** [comment]
When is this going to be added??

**Comment by bora89** [comment]
+1

**Comment by avarnell** [comment]
++

**Comment by phamtuananh791994** [comment]
+1

**Comment by Filson14** [comment]
+1

**Comment by robert-sutton** [comment]
+1

**Comment by tekand** [comment]
@logbon72 can you please merge my pull request?

**Comment by oversio** [comment]
Is it possible that this feature has been eliminated?
to me it does not work after I have updated the component...

somebody can help me?

**Comment by hexadecy** [comment]
@oversio it has been merged long time ago.
@ViDaNgEr and I are working for Beenote, our fork is one year more advanced than this one.
https://github.com/beenote/angular-material-datetimepicker

**Comment by hexadecy** [comment]
@oversio The ng-change is only used in the directive, not the service. And it called once if the date is not the same when the dialog close.
