### ISSUE TITLE
Deprecation warning with moment

### ISSUE THREAD

**Issue by ViDaNgEr** [logbon72/angular-material-datetimepicker#24]
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period).

**Comment by logbon72** [comment]
Thanks @ViDaNgEr !

**Comment by chenav** [comment]
Hey, I can not find the merge branch ( v.1.4.1) on npm. Could you please release it, in order to make it available via bower install ?
Cheers, mate

C.
