### ISSUE TITLE
moment is not defined

### ISSUE THREAD

**Issue by iCoolchar** [logbon72/angular-material-datetimepicker#26]
I followed the steps here: https://www.npmjs.com/package/bower-webpack-plugin
And I run 
`bower install angular-material-datetimepicker`
Add 
`require("momentjs");`
`require("angular-material-datetimepicker");`
in entry.js
run
`webpack -d --watch`
everything is fine. But when I open index.html in the browser, it said
`Uncaught ReferenceError: moment is not defined`
I try the bootstrap demo in the example. It's works fine. I don't know if I forgot anything else or if there is a bug in angular-material-datetimepicker?
Thanks for help!

**Comment by liu-kanghui** [comment]
I ran into the same probelm

I solved it by adding  this line  in my index.html file
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment-with-locales.min.js"></script>`

**Comment by iCoolchar** [comment]
But I use webpack to handle all the js to a bundle.js. And I don't want to especially add a line in the index.html. It's ugly and not reasonable.

**Comment by logbon72** [comment]
Take a look at https://webpack.github.io/docs/shimming-modules.html it recommends how to use global variables. This plugin requires a window object called `moment` from momentjs.

I will assume from the documentation, you can solve this by doing:

```
require("imports?moment=momentjs!angular-material-datetimepicker");
```

If you have any other issues, consult with webpack folks

**Comment by bennekrouf** [comment]
I managed the issue by adding in web pack conf 

```
plugins: [
new webpack.ProvidePlugin({
      moment: "moment"
    })
....
```

**Comment by michellehorn** [comment]
I solved just by putting the moment.js  before the bootstrap-material-datetimepicker.js in the bundle file

**Comment by georgeportillo** [comment]
@bennekrouf, my man.

Thank you sir. Your suggestion worked for me.

What does it do?
