### ISSUE TITLE
Possibility of returning string to model

### ISSUE THREAD

**Issue by lwj5** [logbon72/angular-material-datetimepicker#28]
Not an issue but a suggestion

The date picker returns a date object or a moment object to the model and that makes it difficult to submit  through a form as compared to when it is a string.

e.g. if the ng-model="response". $scope.response in the controller should be a string (not an object).

The moment or date object is technically not needed. You can use parseDate and formatDate to convert string to date and date to string when the datepicker is opened and a date is selected respectively.

**Comment by logbon72** [comment]
Hey, not sure this will work. It's better the model is left as a date, that way it can be easily worked with.
