### ISSUE TITLE
npm package, ownership transfer

### ISSUE THREAD

**Issue by ducin** [logbon72/angular-material-datetimepicker#30]
Hello,

I don't use bower and I needed to use this package under npm. There was no npm package, but I can see package.json file, so I created it [here](https://www.npmjs.com/package/angular-material-datetimepicker). I will happily transfer the ownership if you tell me your logins.

Thanks for the plugin!

**Comment by logbon72** [comment]
My user  ID is logbon72

Regards

**Comment by ducin** [comment]
Ok, Joseph, now you should be an owner of the npm package too, https://www.npmjs.com/package/angular-material-datetimepicker. Thanks.

**Comment by tugrulelmas** [comment]
Hi @ducin, 
Cold you update npm package? Thanks.

**Comment by hexadecy** [comment]
Hi @tugrulelmas, maybe it was a merge mistake but my npm registry was added in the readme of this repo.
https://www.npmjs.com/package/ng-material-datetimepicker

I planned to be at least in sync with logbon72.
