### ISSUE TITLE
How to config the background color

### ISSUE THREAD

**Issue by anthonyhadi** [logbon72/angular-material-datetimepicker#33]
Hi logbon72, This module is very good, I like it. However I want to change the default background color to match my app theme. Can you show me how to do that? Thank you.

**Comment by poojanbabu** [comment]
Hello logbon72,

Can you please tell us how to change the theme of datetime picker to match to that of the current theme being used?

Thank you.

**Comment by Isaac6702** [comment]
Hello, I need also to know how to change the background color.
Thank you

**Comment by dhaval85** [comment]
Use the CSS to change the color. Override CSS as below. 

.dtp div.dtp-date, .dtp div.dtp-time{
    background: red; /\* choose your color */
}

**Comment by Isaac6702** [comment]
Thank you @dhaval85 
following your idea then also I lacked this:
`.dtp > .dtp-content > .dtp-date-view > header.dtp-header {
    background: red;
}
.dtp table.dtp-picker-days tr > td > a.selected {
    background: red;
}

.dtp .dtp-actual-meridien a.selected {
background: red;
}
.dtp .dtp-picker-time > a.dtp-select-hour.selected {
background: red;
}
.dtp .dtp-hand.on {
background: red;
}`

**Comment by Reedyseth** [comment]
> Thank you @dhaval85 
> following your idea then also I lacked this:
> `.dtp > .dtp-content > .dtp-date-view > header.dtp-header {
> background: red;
> }
> .dtp table.dtp-picker-days tr > td > a.selected {
> background: red;
> }
> 
> .dtp .dtp-actual-meridien a.selected {
> background: red;
> }
> .dtp .dtp-picker-time > a.dtp-select-hour.selected {
> background: red;
> }
> .dtp .dtp-hand.on {
> background: red;
> }`

I also have to add styles for this classes to have it fully working:

``` css
.dtp div.dtp-date, .dtp div.dtp-time {
    background: red;
}
```

**Comment by Napster2210** [comment]
Hello guyz,

I have added below classes to override default theme, which will convert green theme(default) to blue theme.
![capture1](https://cloud.githubusercontent.com/assets/17761063/17732939/d785bcda-6491-11e6-9598-ae8a0b5337c7.PNG)
![capture2](https://cloud.githubusercontent.com/assets/17761063/17732970/fa112690-6491-11e6-9655-7cf8219ab2e0.PNG)

```
dtp > .dtp-content > .dtp-date-view > header.dtp-header {
    background: #1565C0;
    color: #fff;
    text-align: center;
    padding: 3px;
}
.dtp div.dtp-date, .dtp div.dtp-time {
    background: #2196F3;
    text-align: center;
    color: #fff;
    padding: 10px;
}
.dtp table.dtp-picker-days tr > td > a.selected {
    background: #2196F3;
    color: #fff;
}
.dtp .dtp-picker-time > a.dtp-select-hour.selected {
    background: #1976D2;
    color: #fff;
}
.dtp .dtp-hand.on {
    background: #2196F3;
}
.dtp .dtp-actual-meridien a.selected {
    background: #1976D2;
    color: #fff;
}
```

**Comment by Reedyseth** [comment]
At the end I ended up using Angular Strap TimePicker because this module does not let you pick the seconds, already requested https://github.com/logbon72/angular-material-datetimepicker/issues/14 though.

**Comment by lakshaybansal** [comment]
I want to change the background-color of the time according to the theme configured in my app using $mdThemingProvider.Very Good Module.Just this Thing I need.

**Comment by phamtuananh791994** [comment]
@Napster2210 , you missing **.** at the begin

```
.dtp > .dtp-content > .dtp-date-view > header.dtp-header {
    background: #1565C0;
    color: #fff;
    text-align: center;
    padding: 3px;
}
.dtp div.dtp-date, .dtp div.dtp-time {
    background: #2196F3;
    text-align: center;
    color: #fff;
    padding: 10px;
}
.dtp table.dtp-picker-days tr > td > a.selected {
    background: #2196F3;
    color: #fff;
}
.dtp .dtp-picker-time > a.dtp-select-hour.selected {
    background: #1976D2;
    color: #fff;
}
.dtp .dtp-hand.on {
    background: #2196F3;
}
.dtp .dtp-actual-meridien a.selected {
    background: #1976D2;
    color: #fff;
}
```
