### ISSUE TITLE
How to programmatically trigger the click 

### ISSUE THREAD

**Issue by OscarAgreda** [logbon72/angular-material-datetimepicker#35]
Great directive, Thanks for sharing it

how you will hack the directive to allow keyboard support, lets say if i press Alt-H , want to popup this awesome date time picker.  

angular.element(elmName).triggerHandler('click');
angular.element(elmName).trigger('click');

none of them work

**Comment by patriceo** [comment]
Hi, I had also the same requirement. After reading the directive code, here is how I workaround this issue:
- First I wanted to hide the widget

`<md-input-container style="display:none;">
                                        <label>Job Start Time</label>
                                        <input mdc-datetime-picker="" date="false" time="true" type="text"
                                               id="startTimeDatePicker"
                                               short-time="true"
                                               placeholder="Time" min-date="minDate" format="hh:mm a"
                                               ng-model="currentPlannedJob.start_date" class="md-input">
                                        </input >
                                    </md-input-container>
`
- Then in my controller code, I send a 'focus' event to the input to simulate a click on it:

`document.getElementById('startTimeDatePicker').dispatchEvent(new Event('focus'));`

I think it would be great to propose this as a "service"

**Comment by logbon72** [comment]
Latest version has `mdcDateTimeDialog`  which can be used to display dialog without an input. It returns a promise which is resolved with the selected date.
