### ISSUE TITLE
Datetimepicker closing modals on which the input field recide

### ISSUE THREAD

**Issue by NiroopGR** [logbon72/angular-material-datetimepicker#36]
This is a great plugin. I found a problem when the datetimepicker is triggered on a modal with a form, it closes the existing form and loads the picker rather than open over it like the material date picker does.

**Comment by NiroopGR** [comment]
skipHide: true, is not updated in the installation file. I am able to get it if I clone the file. Kindly provide new version for installation with the following change.

**Comment by dacasals** [comment]
I have the same error , i have a form inside a modal ,when i put datetimepicker  and click in the field, the modal close , how can i solve this problem, I not understand the last @NiroopGR comment.

**Comment by NiroopGR** [comment]
https://github.com/logbon72/angular-material-datetimepicker/pull/27/commits/4b3ea0ad14b2b7bd531cd6622a904554b35bfd0b

@dacasals This solves the problem of opening the datetimepicker on the modal but another problem is that when you click cancel or close on the picker, the form modal closes instead of the picker.

**Comment by dacasals** [comment]
@NiroopGR yep, you're right, the problem with the cancel button still persists with this solution, then I'm still waiting for a solution.

**Comment by samirgit** [comment]
the datetimepicker is using $mdDialog, thats why it's closing other modals, in angular-material you cannot have more than one opened $mdDialog

**Comment by mandadimuralidharreddy** [comment]
bower this
    "angular-materialDatetimepicker": "https://github.com/logbon72/angular-material-datetimepicker.git#46091900cbd0291504297e7b89cd901848de4c94",

**Comment by blaszek222** [comment]
still doesn't work after bowering

**Comment by logbon72** [comment]
Fixed in recent update
