### ISSUE TITLE
Error: [$compile:multidir] Multiple directives

### ISSUE THREAD

**Issue by bebertz93** [logbon72/angular-material-datetimepicker#37]
Hi,

Thanks for this great lib!
This is my first time to use this lib and I'm encountering an error.
Here's the error on my browser's console: `Error: [$compile:multidir] Multiple directives [input (module: app), mdcDatetimePicker] asking for new/isolated scope on: <input mdc-datetime-picker date="true" time="true" type="text" id="datetime" placeholder="Date" min-date="date" ng-model="dateTime" />`

Hope you can help me with this.

Thanks.

**Comment by logbon72** [comment]
Can't replicate.
