### ISSUE TITLE
Problem using "DD/MM/YYYY" format

### ISSUE THREAD

**Issue by ngarrard** [logbon72/angular-material-datetimepicker#41]
When specifying "DD/MM/YYYY" as format, the datetimepickers date becomes invalid and shows an empty input.
The value I use as date = "2016-05-23T11:20:21.7329621+02:00"

My findings:
Setting the format at line 115: scope.currentDate = moment(scope.currentDate, scope.format); in angular-material-datetimepicker.js, the m.isValid() at line 125 returns false.

**Comment by ceetee** [comment]
I was able to get formatting working correctly by changing line 115 to
 `scope.currentDate = moment(scope.currentDate).format(scope.format);`

**Comment by logbon72** [comment]
- Fixed in most recent update.
