### ISSUE TITLE
Timepicker not displaying in IE 11

### ISSUE THREAD

**Issue by rafaelmagalhaes** [logbon72/angular-material-datetimepicker#42]
Hi i have the latest version of angular material datetimepicker  but the time picker doesn't display correctly on IE 11, 

![image](https://cloud.githubusercontent.com/assets/2240343/15502260/bced08b2-21aa-11e6-92df-83e5ccbecc6f.png)

**Comment by vaughnmuirhead** [comment]
I'm encountering the same issue, have you found a workaround for this?

**Comment by rafaelmagalhaes** [comment]
yeah i did, merge the version 1.4.1 you can find it in the commits, they haven't released that version yet

**Comment by vaughnmuirhead** [comment]
Yep, version 1.4.1 seems to solve the issue. Thanks!
