### ISSUE TITLE
In using min-date and max-date attribute, while selecting date from other months from default selected date month, the calendar scrolls down to the bottom

### ISSUE THREAD

**Issue by veera23456** [logbon72/angular-material-datetimepicker#46]
If i used min-date and max-date attribute, 

while selecting date from other months from default selected date month, the calendar scrolls down to the bottom.

This is because of wrong value of md-top-index in mdcDatetimePickerCalendar directive.

In the line 563 of our js file, we update calendar.topIndex from currentMonthIndex method alone.

var index = currentMonthIndex(nDate);
                  if (calendar.topIndex != index) {
                      calendar.topIndex = index;
                  }

Here we have to subtract calendar.months[0] from currentMonthIndex method to get exact index to set calendar.topIndex so that md-top-index.

So the correct code will be

var index = currentMonthIndex(nDate);
                  if (calendar.topIndex != index) {
                      calendar.topIndex = index - calendar.months[0];
                  }

Kindly fix this issue as soon as possible.
Thanks

**Comment by logbon72** [comment]
Fixed in most recent release.
