### ISSUE TITLE
Datetime picker modal picks time in UTC

### ISSUE THREAD

**Issue by sagarrakshe** [logbon72/angular-material-datetimepicker#49]
In the input box the date time is shown as `2016-06-12 14:10:00` but when I click on the input box to open the datetime picker modal, the time is shown in UTC (in my case UTC-5:30).
So it shows `08:40`. How to fix this?

**Comment by e-500** [comment]
I've obtained the result modifing the code as follow:

`
angular.module(moduleName, ['ngMaterial'])
    .provider('mdcDatetimePickerDefaultLocale', function () {
      this.locale = window.navigator.userLanguage || window.navigator.language;

```
  this.$get = function () {
    return this.locale;
  };

  this.setDefaultLocale = function (localeString) {
    this.locale = localeString;
  };
})}`
```

**Comment by logbon72** [comment]
Thanks for the suggestion, this will be added in subsequent release.
