### ISSUE TITLE
Wierd position

### ISSUE THREAD

**Issue by oleg-demkovych** [logbon72/angular-material-datetimepicker#50]
I have wierd position when open the datetime modal (Appended to top).
http://take.ms/WRLQ6

**Comment by mgween** [comment]
+1

I am also experiencing this issue. The dialog opens near the top of the page instead of near the input.

**Comment by oleg-demkovych** [comment]
Fixed. Need main structure like:

```
<body layout="column">
     <md-content flex>
          <ui-view autoscroll="true"></ui-view>
     </md-content>
</body>
```
