### ISSUE TITLE
Change the DateTimePicker Display Language

### ISSUE THREAD

**Issue by HamzaJridi** [logbon72/angular-material-datetimepicker#51]
can I display the dateTimePicker with the french language? 
 I used the angular-i18n library but it won't work...any help please!!!

**Comment by ljcljc** [comment]
Did you solve this problem? I am facing the same issue.

I found 'picker.param.lang' variable in the source code, and I use 
`<input mdc-datetime-picker date="true" time="false" type="text" id="date" short-time="true" class="value" lang="zh-CN">`

But it still does not work.

**Comment by lakshaybansal** [comment]
Same Issue ?Is the Issue solved?

**Comment by kniort** [comment]
Hello everyone, 

I have the same issue, I just want to display the component with the french language but it doesn't work, it's only display in english 
Here is my code : 
<input mdc-datetime-picker="" date="true" time="true" name="startDate" lang="fr" type="text" id="date time"  placeholder="Date d'ouverture du concours" ng-model="startDate" max-date="endSubmitDate"  class=" md-input" required>
Any solution ? 

Thanks a lot

**Comment by ljcljc** [comment]
Guys. I have solved this issue.

You need to specify the language code like I did previously. And also include the moment local js file.

In my case, it's momentjs/locale/zh-cn.js for Chinese language.

**Comment by kniort** [comment]
Thanks a lot ljcljc it works like a charm !

**Comment by lakshaybansal** [comment]
Hi,
The solution which u gave is not working .Can u please share the exact changes with files also.

**Comment by huilianyi** [comment]
Well. I believe I made it clear before. 
There is something wrong with your code. If you could post your code, I may help you to find the problem.

**Comment by lakshaybansal** [comment]
Hi,
The solution which u gave is not working .Can u please share the exact changes with files also.

**Comment by lakshaybansal** [comment]
<md-input-container>
<input mdc-datetime-picker="" 
 date="true" 
 time="true" 
 id="datetime" 
 placeholder="{{dateTimePickerCtrl.label}}"
 min-date="dateTimePickerCtrl.specificAttr.minDate" 
 ng-model="dateTimePickerCtrl.bindData"
 ng-change="dateTimePickerCtrl.reflectValue(dateTimePickerCtrl.bindData)" 
 class="md-input" 
 ng-class="md-primary"
 lang="zh-cn">
</md-input-container>
I am applying this to the directive and included the file for angular-locale_zh-cn.js

**Comment by brenolf** [comment]
The solution provided by @lakshaybansal did work for me. You should include Momentjs's locale `.js` file.

**Comment by MUNEERALNAJDI** [comment]
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment-with-locales.min.js"></script> 

this file include

example input 

` <input   lang="ar-tn"  
`
to get location code please search inside moment-with-locales.min.js with your langage

**Comment by logbon72** [comment]
Will include solution in README.md

**Comment by joelmm1** [comment]
Scrolling to previous months is not possible

**Comment by hexadecy** [comment]
@joelmm1 this issue is closed...
