### ISSUE TITLE
save only time in model

### ISSUE THREAD

**Issue by umair-khanzada** [logbon72/angular-material-datetimepicker#55]
Hi, 
there is any way for store only time value in ng-model ?

**Comment by agyrafa** [comment]
@umair-khanzada  did you managed to do this?

**Comment by umair-khanzada** [comment]
you can apply custom filter.
Or 
`var time = new Date().getTime()` and apply time filter.

**Comment by agyrafa** [comment]
thanks, i got it :)

**Comment by umair-khanzada** [comment]
my pleasure
