### ISSUE TITLE
DateTime popup not displaying properly (CSS Not loading)

### ISSUE THREAD

**Issue by watat83** [logbon72/angular-material-datetimepicker#59]
I have tried to integrate your library into my app, but unfortunately the css is not loading properly. When the popup load the css is not being applied to it. I even made sure that the CSS for the popup was loading before bootstrap. 
Should I also include other files such as: [beautifier.js](http://jsbeautifier.org), and [highlights](https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js) and their appropriate CSS files? Because I did but still not getting what I expected.
![mddatetimepopup](https://cloud.githubusercontent.com/assets/8031031/17275373/1481a0c6-56ba-11e6-9a9f-5d5dc44a8a64.JPG)

**Comment by VickeyC** [comment]
I had the same problem, then I discovered that I was missing the "rel=stylesheet" clause in the datetimepicker.css link.   Maybe this will fix your problem also.
