### ISSUE TITLE
Closes already open popups when coming to for front of the screen

### ISSUE THREAD

**Issue by MADavies** [logbon72/angular-material-datetimepicker#60]
The datetime picker is being called from another modal popup and is forcing the original popup to close stopping me from returning to the original popup to continue what i was doing. Would it be possible to add a skipHide:true to the date time picker popup modal or some other method to stop the pop up from prematurely closing the parent modal popup?

**Comment by theRichu** [comment]
+1

**Comment by Owizardo** [comment]
Having this exact issue, which is breaking my form design +1

**Comment by blaszek222** [comment]
+1

**Comment by MUNEERALNAJDI** [comment]
yes, you can by using css 
<style>                                        
.md-dialog-container{ z-index: 9999;  }
</style>
 befor input

this way works with me
