### ISSUE TITLE
Clear Date

### ISSUE THREAD

**Issue by hemantvikram** [logbon72/angular-material-datetimepicker#63]
Hi,

How can I clear the date from the input field?

Thanks,
Hemant.

**Comment by zjda** [comment]
Same question here.  Also, want to have Today button.  

Thanks,
-ZJ

**Comment by the1drewharris** [comment]
Same question here. Just need a way to clear the date back to null.

**Comment by logbon72** [comment]
Today button has been added in most recent release, to clear, date, please add another button outside dialog to set model to null. Won't want to have too many buttons on the dialog.
