### ISSUE TITLE
Is this working in md-dialog box?

### ISSUE THREAD

**Issue by nirmal-solanki** [logbon72/angular-material-datetimepicker#64]
Is this working in md-dialog box?
I want to used  angular-material-datetimepicker in mg-dialog box.
But, mg-dialog box close when angular-material-datetimepicker time/date picker open.

there is any way to use angular-material-datetimepicker in mg-dialog box?

**Comment by helmut-hoffer-von-ankershoffen** [comment]
cp. http://webiks.com/mddialog-with-a-confirmation-dialog/

**Comment by mandadimuralidharreddy** [comment]
using master branch it will work. Latest updates are yet published in bower.

**Comment by logbon72** [comment]
Please use v1.5.x
