### ISSUE TITLE
Outdated bower repository

### ISSUE THREAD

**Issue by EricDosReis** [logbon72/angular-material-datetimepicker#68]
$mdDialog option 'skipHide: true' is not setted in the Dialog config object. This option allows the datetime picker dialog open above another dialog.

Another interesting config is 'clickOutsideToClose: true', this option allows the dialog is closed when clicked outside or when escape key is pressed.

**Comment by logbon72** [comment]
This has been fixed in recent release.

**Comment by EricDosReis** [comment]
Thanks dude!
