### ISSUE TITLE
Type date instead of open a modal

### ISSUE THREAD

**Issue by marciogurka** [logbon72/angular-material-datetimepicker#74]
Is there a way to choose type a date instead of automatically open a modal when the input get focused???  Like have a button side-by-side in a input, and the modal opens when the users click that button, but if the user prefer, he can type manually a date/time (like using a directive to mask or something like that)?

**Comment by blaszek222** [comment]
+1

**Comment by alobban** [comment]
I would love to have the option to type in date-time or select date-time from the modal. 
Is there a PR for this?

**Comment by logbon72** [comment]
See the comment here: https://github.com/logbon72/angular-material-datetimepicker/issues/85
