### ISSUE TITLE
Modal inside another modal

### ISSUE THREAD

**Issue by fabio-barboza** [logbon72/angular-material-datetimepicker#75]
Greetings,

Is it possible to add this parameter "skipHide: true" in the $mdDialog.show call?

              $mdDialog.show({
                  template: template,
                  controller: PluginController,
                  controllerAs: 'picker',
                  locals: locals,
                  openFrom: element,
                  parent: angular.element(document.body),
                  bindToController: true,
                  disableParentScroll: false,
                  skipHide: true
                })

This gonna make possible to show the DatePicker modal inside of another modal.

Regards,

Fabio

**Comment by blaszek222** [comment]
I think this is the duplicate of #60

**Comment by logbon72** [comment]
Fixed in most recent update.
