### ISSUE TITLE
jQuery is not a function

### ISSUE THREAD

**Issue by tugrulelmas** [logbon72/angular-material-datetimepicker#82]
I don't use jQuery but I use a chrome extension that adds a jQuery property as undefined on `window`. There is an [if condition](https://github.com/logbon72/angular-material-datetimepicker/blob/gh-pages/js/angular-material-datetimepicker.js#L12) to determine whether jQuery is installed. There is no check to see if jQuery is undefined. That's why the `jQuery is not a function` error occurs when jQuery is undefined. Removing jQuery completely from here may be a better option.

![image](https://cloud.githubusercontent.com/assets/3829187/22244916/2307fdcc-e236-11e6-8b40-79bbadda7e95.png)

**Comment by logbon72** [comment]
jQuery dependency has been removed.
