### ISSUE TITLE
problem with rtl website

### ISSUE THREAD

**Issue by mohammadkhoeini** [logbon72/angular-material-datetimepicker#91]
when web page default direction is rtl this problem comes up
![capture](https://cloud.githubusercontent.com/assets/11052733/22861028/c1d3a7d4-f123-11e6-832f-24b293b6873e.PNG)

i fix this with this css change 
.dtp div.dtp-picker-clock {
    margin: 10px 20px 0 20px;
    padding: 10px;
    border-radius: 50% !important;
    background: #eee;
    direction: ltr;  // this one
}

result:
![capture](https://cloud.githubusercontent.com/assets/11052733/22861040/00661554-f124-11e6-8272-7446a20e4baa.PNG)

thanks for your great work

**Comment by hexadecy** [comment]
@molikh Is it ok?
Add to material-datetimepicker.css:
```
html[dir="rtl"] .dtp div.dtp-picker-clock {
    direction: ltr; 
}
```

Set in your app.js:
`document.documentElement.dir = "rtl"`
or 
`<html dir="rtl">`

**Comment by mohammadkhoeini** [comment]
@hexadecy no it's not.
there is 3 way to specify direction.
1- use dir="rtl" on html ( your solution only fix this)
2- use dir="rtl" on body tag ( i use this )
3- use css direction="rtl" ( can be used anywhere)

so your solution dosent fix problem in all kind of directions

ty for your response

**Comment by hexadecy** [comment]
Your fix was better.
