### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by hexadecy** [logbon72/angular-material-datetimepicker#93]
Great project
Do you want some help keeping this repo up-to-date?

- Like updating the [npmjs](https://www.npmjs.com/package/angular-material-datetimepicker)
- Merging some pull request
- Closing issues
- Making a request for cdnjs
- New cool features

**Comment by hexadecy** [comment]
I fixed most of the issues / requests and more:
- 24 hours clock 
- Mouse/touch move
- Nearest minute steps 1, 5, 10, 15 ...
- Seconds view clock

**Comment by hcbelias** [comment]
@hexadecy  I would like to implement minute-steps directive. How can I start?

**Comment by hexadecy** [comment]
Name | Type | Description
-- | -- | --
minute-steps | Number | 1 to 59 minute steps (default: 5)

You can use our fork:
https://github.com/beenote/angular-material-datetimepicker
