### ISSUE TITLE
minDate and maxDate mixed up

### ISSUE THREAD

**Issue by fabienbranchel** [logbon72/angular-material-datetimepicker#96]
When we use two datetimepickers on same page, minDate and maxDate are mixed up.
You can test it on your demo, in the DateRange Example : https://logbon72.github.io/angular-material-datetimepicker/

1. Select a start date. 
2. Reopen the start date : all is ok
3. Open the end date : we can't select date before start date, all is ok
4. Select the end date.
5. Reopen the start date : we can't select a date before than start date we previously selected
6. Reopen the end date : we can't select a date after than end date we previously selected

**Comment by hexadecy** [comment]
As a workaround you have to set undefined attribute min-date or max-date.
min-date="null" 
Not sure it's the best solution...

**Comment by hexadecy** [comment]
@fabienbranchel can you test in my fork?

**Comment by fabienbranchel** [comment]
@hexadecy thank you, seems to work ;-)
